### ISSUE TITLE
BOX command disappeared

### ISSUE THREAD

**Issue by RikT** [liaralabs/swizzin#101]
after a reboot I went to remove plex via box command but upon entering the command it errored as shown in the image below just wondering if you maybe able to shed some light on it at all using ubuntu 18.04  

![untitled](https://user-images.githubusercontent.com/732290/39677080-1a079ca8-516d-11e8-8b46-06204ed1abca.png)

**Comment by maximeloizeau** [comment]
This looks like to be the same issue as there: https://github.com/liaralabs/swizzin/issues/72

I just had it as well

**Comment by liaralabs** [comment]
I'm assuming you guys are:

a) running bash
b) the file /root/.bashrc exists
c) /root/.bashrc contains `export PATH=$PATH:/usr/local/bin/swizzin`

**Comment by RikT** [comment]
Yes bash running the /root/.bashrc exists and contains relavent paths

**Comment by liaralabs** [comment]
I can't replicate this issue on a fresh install of 18.04 on a vultr testbed.

Do you have a .profile in root? If so, what are the contents?

**Comment by RikT** [comment]
I have reinstalled the server now so no file now :/

**Comment by liaralabs** [comment]
There's no .profile after a fresh install? This could be your issue. I moved the path settings which were originally in .profile to .bashrc because of compatibility; however on my test server there was a .profile which sourced .bashrc on login.

I don't actually touch that file anymore, but it seems like your os template might be missing this.

Who is your provider?

**Comment by RikT** [comment]
No I meant I do not have the files from the old install lol as I have since reinstalled

**Comment by liaralabs** [comment]
Closing as this should be fixed and there have been no further updates. If this issue persists for any, please re-open or create a new ticket.
