### ISSUE TITLE
ruTorrent requires nginx?

### ISSUE THREAD

**Issue by forteefi** [liaralabs/swizzin#112]
Hi, 

I use Caddy web server, and like that swizzin is 'modular'. But when I try to install ruTorrent, it complains that no nginx is installed.

Are there plans to remove the nginx part from the script for ruTorrent? In the mean time I'm using Flood since no web server checks are made there, and I can set it up myself in my Caddyfile later.

**Comment by liaralabs** [comment]
It's essentially expected that users who are installing this suite aren't going to be installing their own web server, so this isn't going to be altered. Flood uses a built in web server, whereas ruTorrent requires a web server to work. This check exists so that people don't install ruTorrent without a web server and flood my inbox with tickets about why ruTorrent doesn't work. 😉 

I recommend looking into commenting out the checks for nginx and removing the associated nginx conf bits in scripts/nginx/rutorrent.sh
