### ISSUE TITLE
Concerns about the project

### ISSUE THREAD

**Issue by LWSRep** [liaralabs/swizzin#12]
Hi

We have been using quickbox for a long time now but it seems to have been ended lately.
Reading some articles about why they quit made me wonder if this project might undergo the same fate and to avoid that maybe i or we, could assist in avoiding that.
I would appreciate it if an admin/dev could contact me personally to discuss some options as we would hate to see this project suffer the same fate.
Maybe there is something we can do to support the project.

Kind regards
Thomas Carter

**Comment by d2dyno** [comment]
This isn't an issue. Please try posting a thread on reddit perhaps: https://reddit.com/r/swizzinltd or join the swizzin IRC: irc.swizzin.ltd:6697 #swizzin

**Comment by liaralabs** [comment]
Thanks @d2dyno. IRC and/or reddit are indeed the proper places for discussions such as this. However, I know this is something that is on everyone's mind, so I will allow this and then this issue will exist into perpetuity for posterity.

-------------------

I understand your concerns. If things had been different I may have focused my energy on maintaining QuickBox rather than forking aspects of it and moving on.

Please understand that there is only one dev: myself. I have no plans of abandoning the project at the moment; however, life can always unexpectedly crop up. Open source projects end up without maintainers frequently.

I have 2 jobs (which I love). However, neither are your typical 9-5. My schedule varies wildly from week to week. I am often busy and take days off as they come, rarely as I schedule them. I devote energy to the project when I have time and when I am in the mood.

That said, I have taken note of some of the issues faced by QuickBox at the moment and am taking steps to avoid pitfalls of the current QB situation.

At this time, I have no plans to expand the core services and documentation of swizzin outside of github: the wiki (as it gets built) will remain on github as a source of knowledge even in the event that something happens to me. The website (https://swizzin.ltd) is auxiliary and provides no extra information than what is already available on the github. If it were to disappear, the project would lose nothing (unlike the great stores of knowledge that were on the qb forums).

Further, a large gripe of QB was how ridiculously complex the repository was. I hope that anyone who has examined the code has noticed that the complexity of this whole machine has been cleaned up significantly and elegantly.

- The installer does not run a separate set of code to install a package during installation versus post-install. (The installer is basically a customized iteration of `box`)
- The size of the repo has been drastically reduced.
- Functions are not spread out over many files (with the exception of the nginx installation hooks)
- Package files are contained entirely within their appropriate scripts. There is no "template" directory

Things are largely where you would expect them to be.

I **do not** want this project to become complicated and am actively looking into solutions to make things easier to maintain going into the future (like removing the QB Package Manager from the dash). The more complicated it becomes, the more time it takes to maintain.

However, if you're interested in supporting the project, there are definitely things you can do:

- Donate. Not just with money! You have no idea how valuable the hashes your idle cpu could be making are to me. The project will take lower priority if I need to earn money to pay my bills and can't justify spending my time on the project. If the project provides me with funding, I have more incentive to devote time to it.
- Contribute!
  - Write your own packages to be pulled in
  - Test the project and make thorough, detailed bug reports
  - Help create and keep wiki pages up to date and relevant
  - Become involved in the community.

I know my limits and I know what I have time to commit to - what will burn me out and what will give me energy. As I have told others, I have *zero* interest in maintaining a community. I do not have time to be a community liaison, answering questions and moderating trolls in addition to developing the project. I have committed to be the dev of this project - not much else :smile: 

Further, I am exploring ways to incentivize donating (with a patreon or such), perhaps by allowing donators to access a premium repository of scripts.

I hope this helps answer some of your concerns. As always I remain available for contact in irc (irc.swizzin.ltd @liara)
