### ISSUE TITLE
Possible Ubuntu install issue due to lack of storage

### ISSUE THREAD

**Issue by jcroy** [liaralabs/swizzin#177]
So I'm testing right now to see if this is an issue on my end or swizzin. But when I install swizzin install didnt complete properly (but said finished) due to lack of space on device.  Given that I allocated 64gb of disk space on Proxmox to my VM I would be surprised.  Im playing around with partitions on my out of the box server install to see if I can fix it.  Having the ability to change install paths if possible would be handy if possible.  I might be miss understanding things so feel free to correct me if I am.

**Comment by liaralabs** [comment]
Install paths can't really be changed, unfortunately. There is a set way of doing things and installing applications to paths (eg /usr/local/bin for user compiled applications). My recommendation is to ensure your root partition has enough free space (at least 30 gb) because Plex by itself can create a large Library if you have a lot of media.

Otherwise, 64GB should be plenty, assuming your root partition is large enough. I suspect there might be other issues at play.
