### ISSUE TITLE
Adding (sub)domain to IP address

### ISSUE THREAD

**Issue by bumjrah** [liaralabs/swizzin#18]
I ran letsencrypt prompts and it generated the certs onto my nginx confs nicely. However I thought the IP domain linking would be an automatic process once nginx reloads. Is there anything more I am required to write? Or did I miss a step?

The domain name is active on cloudflare. And I can access the dashboard through my IP. Any help would be appreciated.

**Comment by d2dyno** [comment]
I'm not exactly sure what the issue is. Are you saying you want to access your panel, through a subdomain (swizzin.example.com)?

Also, I'm assuming you have an A/CNAME record, with the subdomain you want, correct? Should be 'A' if you use a different IP for the subdomain than the primary domain, or 'CNAME' if you use the same IP for both.

**Comment by liaralabs** [comment]
swizzin is not responsible for anything to do with name records or anything of the sort.

If the DNS entry isn't pointing at your IP, ensure you have no duplicate entries. Beyond that, ips often take time to propagate. It's entirely possible your router or local DNS resolver is still caching the old value.

**Comment by bumjrah** [comment]
Sorry for the above vague descriptions. Did a bit of googling & found out the cause. Everything was setup okay. When I changed the cloudflare SSL from "Flexible" which is the default to "Full", I got the domain working. Thanks guys for the replies :)
