### ISSUE TITLE
Add SonarrV3/Phantom-Develop Install Option

### ISSUE THREAD

**Issue by theoneandonlyewok** [liaralabs/swizzin#190]
Sonarr V3 is amazing. Would be cool if we could install the V3 Version out of the box in Swizzin.

**Comment by liaralabs** [comment]
I don't tend to support beta software in a stable branch because I don't have time to keep up with potential breaking issues that can change at any time before release.

However, since the sonarr repo is added during the install of Sonarr v2, it looks like you should simply be able to install the package `sonarr` vs `nzbdrone` (v2).

Configuration, etc, would be solely up to you at this time though.

**Comment by McSon2** [comment]
Is it easy to do this ? How can I do ?

**Comment by tenknas** [comment]
Same question, how do I install sonarr v3 on swizzin?

**Comment by userdocs** [comment]
This is a functional method.
https://github.com/userdocs/swizzin/blob/master/scripts/install/sonarr3.sh
https://github.com/userdocs/swizzin/blob/master/scripts/nginx/sonarr3.sh
https://github.com/userdocs/swizzin/blob/master/scripts/remove/sonarr3.sh

Waiting for it to not be in beta.
