### ISSUE TITLE
Rutorrent timing out

### ISSUE THREAD

**Issue by electronicous** [liaralabs/swizzin#193]
I selected it to install rutorrent, rtorrent, plex and nginx. After it finished installing i rebooted and tried opening the link that the script gave `https://<username>:<pass>@<IP>` but it just keeps loading the page until it times out. rtorrent is running in a screen on port 22459. I tried adding that port to the IP but same thing happens `https://<username>:<pass>@<IP>:22459`.

**Comment by liaralabs** [comment]
ruTorrent is at 

https://<IP>/rutorrent

You cannot connect directly to the port -- that is not how r(u)Torent works. If you connect to https://<IP> it should bring up the panel (if installed); otherwise, you'll see a 401 Forbidden error on your webroot (this is intentional).

Assuming nginx/php-fpm are up and running, timeouts to this page could be indicative of a local socket issue (or perhaps a php-fpm resource issue -- you can check /var/log/php7.{0,2)-fpm.log (0 or 2 depends on the OS you're running)
