### ISSUE TITLE
Box upgrade not working

### ISSUE THREAD

**Issue by LaMpiR** [liaralabs/swizzin#197]
Still not upgrading :) Any news?

This is the output, but it doesn't upgrade it.

root@xxx:~# box upgrade plex
Updating swizzin local repository
M       scripts/install/wireguard.sh
M       scripts/remove/tautulli.sh
M       scripts/remove/wireguard.sh
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at dad1476 How did this get here?
Already up to date.
/etc/swizzin/scripts/update/lounge.sh: line 21: thelounge: command not found
Updating panel
From https://github.com/liaralabs/quickbox_dashboard
 * branch            master     -> FETCH_HEAD
Already up to date.
HEAD is now at 65f8719 updated css aesthetics to address overlapping
Already up to date.
Upgrading plex

**Comment by liaralabs** [comment]
Have you already used the upgrade plex command in the past?

`box upgrade plex` is a one time command which installs the github script from here: 

https://github.com/mrworf/plexupdate

If you've already installed the update plex script, then it should be configured to run automatically. If you want to run a manual check, then run `/opt/plexupdate/plexupdate.sh`

Otherwise, I can see no indication that the script isn't functioning as it should. Upgrade plex isn't meant to upgrade plex on-demand -- it's meant only to install the background checks that will run according to your setup that you define during setup
