### ISSUE TITLE
Issue "some" OS

### ISSUE THREAD

**Issue by kanenses** [liaralabs/swizzin#2]
Hello,

I have some issues with dedicated servers with SSD driver and Debia 8.9 and Ubuntu 16.04.3

Servers from servdiscount.

The bos get alot of erros for startm NGINX. It is possible and a pre check requisites?

**Comment by lizaSB** [comment]
Would it be possible for you to upload the install log or give me access to your botched installation? So far the only errors for nginx have been a result of providers shipping the server preinstalled with Apache. I perform some checks to try to detect Apache, but they might be failing.

Some providers use custom templates that behave in ways that I don't expect. The best way for me to hammer out details like this is to have direct access to troubleshoot why things are failing.

**Comment by liaralabs** [comment]
Would it be possible for you to upload the install log (`/root/logs/install.log`) or give me access to the botched installation? The most notable reason that nginx would error at the moment is due to a pre-existing apache2 install. I perform a check that should account for this, but it might not be perfect in all cases.

That said, having direct access to troubleshoot would be ideal :) If you are willing to drop me your credentials, you could find me in irc (irc.swizzin.ltd #swizzin) or email me at liara@swizzin.ltd.

**Comment by kanenses** [comment]
Sorry for late reply, after lastest updates you have made and script, I succeful installed and run awesome...

I have a issue, my drive for saving data is not under /dev/sda but under /dev/sdb

How can I change the usage of space on main board of panel (quickbox theme).

**Comment by liaralabs** [comment]
The panel reads either / (root) or /home

It shouldn't matter if /dev/sda or /dev/sdb is mounted, as long as sdb mounts at one of these two points.
