### ISSUE TITLE
fresh install error

### ISSUE THREAD

**Issue by foxan54** [liaralabs/swizzin#208]
Hello,
Sorry for my bad english
the last week i had install swizzin script and all were working properly on ubuntu 18.04 LTS.
I'm trying to reinstall on a new server but impossible to always rutorrent down and Jackett remains in "installation"

i don't know why.

**Comment by liaralabs** [comment]
Please check through the issues before posting a new one. The jackett install issue has been documented [here](https://github.com/liaralabs/swizzin/issues/156) and I haven't had time to look for a fix on why the config file isn't being generated in certain scenarios as none of my tests have been able to reproduce the error.

As for ruTorrent, there should be no issues. Have you restarted the server since the installation? A few services typically need to be restarted before the installation is ready to use and a server reboot generally just puts your machine in a fresh state.

**Comment by foxan54** [comment]
Sorry I did not look for jackett since last week it worked
For rutorrent I reboot the server and refresh via the panel 

I will try a new install

**Comment by liaralabs** [comment]
Which version of rTorrent did you choose during installation? Last I am aware, there are issues building the feature-bind branch on Ubuntu and am uncertain if those issues have been fixed upstream yet.

**Comment by foxan54** [comment]
i use feature-bind so i will try other branch

**Comment by foxan54** [comment]
i have try with debian 9 I have the same problem.

**Comment by foxan54** [comment]
all works i reinstalled ubunutu 18.04 LTS
for jackett i installed rutorrent + flood in the 1st install (before I did that with rutorrent)
for nextcloud I copy an old nextcloud.sh into the install folder

**Comment by liaralabs** [comment]
The nextcloud script had a syntax error which has since been fixed. Further compatibility for the jackett script has also been improved in this time. I encourage users to open new issues if they are facing issues with Jackett still.
