### ISSUE TITLE
Nextcloud - warnings regarding your setup.

### ISSUE THREAD

**Issue by zanesavage** [liaralabs/swizzin#209]
I have been scratching my head for days trying to figure this out, and am finally caving to see if anyone can assist.

I've installed:
NGINX - PANEL - OMBI - NEXTCLOUD

I'm also using cloudflare if that makes a difference; have all the bells and whistles pretty much turned on for cloudflare.

The only issue I'm having is the Nextcloud warnings:

PHP does not seem to be setup properly to query system environment variables. The test with getenv("PATH") only returns an empty response. Please check the installation documentation ↗ for PHP configuration notes and the PHP configuration of your server, especially when using php-fpm.
The PHP memory limit is below the recommended value of 512MB.
MySQL is used as database but does not support 4-byte characters. To be able to handle 4-byte characters (like emojis) without issues in filenames or comments for example it is recommended to enable the 4-byte support in MySQL. For further details read the documentation page about this.
The "X-Robots-Tag" HTTP header is not set to "none". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "X-Download-Options" HTTP header is not set to "noopen". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "X-Permitted-Cross-Domain-Policies" HTTP header is not set to "none". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "X-XSS-Protection" HTTP header doesn't contain "1; mode=block". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
No memory cache has been configured. To enhance performance, please configure a memcache, if available. Further information can be found in the documentation.
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
intl
imagick
The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" or "same-origin". This can leak referer information. See the W3C Recommendation ↗.

I can see that the Nexloud conf is showing:

# Adding the cache control header for js and css files
    # Make sure it is BELOW the PHP block
    location ~ \.(?:css|js|woff|svg|gif)\$ {
        try_files \$uri /nextcloud/index.php\$uri\$is_args\$args;
        add_header Cache-Control "public, max-age=15778463";
        # Add headers to serve security related headers  (It is intended
        # to have those duplicated to the ones above)
        # Before enabling Strict-Transport-Security headers please read
        # into this topic first.
        # add_header Strict-Transport-Security "max-age=15768000;
        # includeSubDomains; preload;";
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;
        # Optional: Don't log access to assets
        access_log off;

The headers are there but nothing. Any assistance would be really appreciated.

Should I be putting the headers in the nginx.conf file (which I've tried and I get a great website score on firefox) but Nextcloud still shows same warning.

Cheers

**Comment by liaralabs** [comment]
In my (limited) experience regarding web development, I have come to learn that CloudFlare is typically the root of any and all problems when things *should* work but *simply don't*. CloudFlare is often doing all sorts of things that you may not even be aware of in terms of caching and attempting to improve performance.

I've often attempted to dev websites and have found that during development there is absolutely no reason to keep the CloudFlare proxy enabled because their aggressive caching can be a real nightmare if you're altering files on the server. The *last* step should be to enable cloudflare, not your first.

However, there are some things that sound like there may be a configuration issue on your server. Have you installed your own version of PHP on the server or have you let an update to php overwrite the php.ini? The memory limit of PHP should be 768MB on a default install. (https://github.com/liaralabs/swizzin/blob/master/scripts/install/nginx.sh#L74-L86)

In regards to the missing php extensions, it's entirely possible they aren't present. I don't keep the NC script super up to date as I don't currently use NC on my own servers. Thus when new versions are released with new requirements, the script may not be updated to account for it. You should be able to install the missing modules with `sudo apt install php-imagick php-intl`.

My suggestions for the headers:
- Disable CloudFlare (turn the icon from Orange to Gray in your DNS settings for the domain in question)
- Make changes to the disk
- Restart php7.0-fpm (or 7.2 if using ubuntu 18.04) after making changes to files on the disk
- Reload or restart nginx after making configuration changes

If things start working without CloudFlare, *then* start trying to make things work with CloudFlare.

CloudFlare is likely messing with your headers -- I really wouldn't be surprised

**Comment by liaralabs** [comment]
Closing due to lack of update following suggestions.
