### ISSUE TITLE
Few problems with flood

### ISSUE THREAD

**Issue by Marbellasaad** [liaralabs/swizzin#210]
Hi,

I'm "pretty new" to "seedbox managing" and i got a problem.

I tried to install rtorrent myself but since i got an error with compiling i used your script.
First i had some problems,when i installed rtorrent with "feature-bind" i couldn't get rtorrent started. After a "few" reinstalls and versions it work.

When i tried to install medusa/sonarr/radarr everything was right except for a single thing : swizzin wouldn't give me the port which he installed medusa/sonarr/radarr on,but after some googling i've found the default port and everything was right.

But now is the part where i have a problem actually,i need a SCGI to HTTP Proxy,after i googled i've found that i needed nginx to manage that. I've also found that nginx is a web-server who act like a proxy,like you go on serverip/radarrr and it redirect you to radarr which is on serverip:8081.

So i installed nginx,it automaticly detected flood (at this point i removed radarr/sonarr and medusa from my server) so i was like "it's nice" and i guessed url would be myserverip/flood,i guessed right but here is the problem : My flood webpage is actually blank and every url i try to access redirect me on HTTPS with a red error on chrome (which is normal since i don't have any https certificate)

Here is logs on chrome console :
```
ServerIP/:1 GET https://ServerIP/static/css/main.3c0817dd.css net::ERR_ABORTED 404 (Not Found)
ServerIP/:1 GET https://ServerIP/static/js/main.04667056.js net::ERR_ABORTED 404 (Not Found)
```

And here is actual blank page source code :
`
  | <!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" href="/favicon.ico"><title>Flood</title><link href="/static/css/main.3c0817dd.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="app"></div><script src="/static/js/main.04667056.js"></script></body></html>
-- | --
`

I think the problem is simply : it try to access the JS file but on HTTPS when it's not setup and since flood doesn't work without JS well then it display a blank page.

Idk if it's the best place to ask but i would like some advices,i think the thing to do is to disable HTTPS redirection but i don't know if it's global to nginx or if it's the flood config that i need to rewrite.

And i have another question :  If nginx is simply a proxying webserver,why is flood not accesible on his port ?

And btw,thanks for your awesome work.

**Comment by liaralabs** [comment]
Sorry for the issues with rTorrent -- the feature-bind branch is a bit broken at the moment, which is why 0.9.6 and 0.9.7 have been enabled for all versions now (it used to be feature-bind only until the issues came back)

When I enable the nginx proxy, I disable port access as a rule of thumb. This is because most of the applications can be accessed directly at their ports without further authentication and it would be a security issue unless the user sets up their own authentication after the fact.

If people saw an auth dialog on the front end, they might not even realize that there's a second, unauthenticated backend they're not fully aware of, thus this is the default behavior.

If you're wondering exactly what happens when the proxy is enabled on the application then you shouldn't need to look further than the scripts in the scripts/nginx folder.

Flood is a bit of an odd one because the webroot is "built" into the application, so you can't just remove it from your configuration and expect that it would be gone because the js and css paths are set during npm build.

In order to remove it, you need to make the changes in /home/<user>/.flood/config.js and then rebuild flood with

```
u=<username>
cd /home/$u/.flood; npm run build
```

These are the lines in responsible for the changes, in case you're curious: https://github.com/liaralabs/swizzin/blob/master/scripts/nginx/flood.sh#L56-L64

**Comment by Marbellasaad** [comment]
Thanks you,so if i understand well,i only need to modify flood build so instead of going to https://server it go to http ?

I mean from what i've seen on index source code the problem is they locate resources using .. instead of "absolute" files so i just modify baseURI: '/flood' to baseURI: 'http://myserverip/flood' but i think there is some problems if i would do that since chrome forbid from going to https to http.

Isn't there a way to simply desactivate https redirection ?

Thanks a lot liara.

**Comment by Marbellasaad** [comment]
Yeah that was i was thinking,after i did what i said (modifying base path),files are at their correct place but chrome warn me :
ServerIP/:1 Mixed Content: The page at 'https://ServerIP/flood/' was loaded over HTTPS, but requested an insecure favicon 'http://ServerIP/flood/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

**Comment by liaralabs** [comment]
I'm not sure I understand the problem you're having now?

**All** connections over nginx are upgraded to https from http, we don't allow serving content insecurely as it's a security issue and leaves you pushing your credentials around unencrypted.

In the default setup, all applications use http on the backend because they are never accessed through the proxy unless it's through localhost (you don't need to use https on localhost connections because the data never leaves the server). Nginx then serves the content with https because the connection is leaving the server.

A lot of proxies actually break completely if you try to enable https on the proxy end of things.

But coming back to my original point, if the nginx proxy is enabled, all connections will be upgraded to https and there shouldn't be any room for mixed content errors. If you're having mixed content issues with the proxy off, then you need to ensure that https is actually enabled for the application in question (and for many apps, this typically requires assigning the certificate to the application directly). Most applications will have a setting to enable https (which you should only do if nginx is not proxying the data).

**Comment by Marbellasaad** [comment]
Ohh my bad i completly missunderstood the problem. I was thinking Flood didn't had any HTTPS support so everything who wasn't http would get me into a 404 but that was simply a location problem.

I modified baseURI to "/flood" and it work well now.
Thanks a lot liara
