### ISSUE TITLE
deluser issue

### ISSUE THREAD

**Issue by an0n666** [liaralabs/swizzin#217]
It doesn't check for user name. I didn't enter any username and it deleted all of my files. Just wow -_-

**Comment by liaralabs** [comment]
Apologies for the issues. Clearly the script was never intended to be used
without a user argument. A lot of box commands won't run if certain
criteria aren't met -- I never considered the possibility someone would
forget to add a user to the argument though... I'll add some checks to make
more resilient in that regard.

However, the deletion script already does at least check and force you to
press enter to confirm the command before it runs and gives you a chance to
back out before continuing, so it's not like the command just blows your
data away without any form of confirmation. It's always prudent to slow
yourself down and double check when running data deletion commands on
Linux, simply because deletion commands can be dangerous if misused.

**Comment by an0n666** [comment]
I thought it would prompt me to enter username after the warning message. Or if no username was present it would show an error. But it went ahead anyway.
