### ISSUE TITLE
NGINX ERRORS last version update with php file

### ISSUE THREAD

**Issue by ajvulcan** [liaralabs/swizzin#223]
/etc/swizzin/sources/functions/php: line 2: $'\r': command not found
/etc/swizzin/sources/functions/php: line 3: syntax error near unexpected token `$'{\r''
'etc/swizzin/sources/functions/php: line 3: `function restart_php_fpm () {
/usr/local/bin/swizzin/install/nginx.sh: line 263: restart_php_fpm: command not found

**Comment by liaralabs** [comment]
What does `/etc/swizzin/sources/functions/php` look like?

```
line 2: $'\r': command not found
```

Leads me to believe your php function file got converted to windows (CRLF) format instead of unix (LF) format because line2 is empty and `\r` is the newline character in CRLF (rather than \n). I don't have any issues using this file on a fresh checkout, so the repo itself is likely not at fault here.

You can use the program dos2unix to convert them and they should work after.

**Comment by ajvulcan** [comment]
yes, true, thanks.
