### ISSUE TITLE
Option to install rtorrent without compiling

### ISSUE THREAD

**Issue by ahmedtds** [liaralabs/swizzin#228]
Is it not possible to install rtorrent without actually compiling it from source?

When I try to install it on a 512MB server it installs succesfully but when I try to install on a 256MB server it fails. It can actually build libtorrent but it fails at the building stage of rtorrent. So I assume it's because of insufficent memory.

It would be nice to have an option to install it without compiling it from scratch.

Thanks

**Comment by liaralabs** [comment]
Currently no, most users I find are pretty picky about their rTorrent version and don't tend to be satisfied with the version in repositories. The repo option in deluge is largely a fragment I never removed from the fork because some people requested it.

How much free ram do you have when booted into the OS? Do you have any swap? I'm not opposed to adding a repo option, but I worry your machine with 256MB doesn't have enough ram to run a torrent client at all.

Each upload slot will take a varying amount of ram (depends on chunk size, could easily be 1mb or even larger). Thus, with a torrent with 2mb and 50 upload slots would be 100mb of RAM. You could easily run OOM in this scenario.

**Comment by ahmedtds** [comment]
> The repo option in deluge is largely a fragment I never removed from the fork because some people requested it.
I'm glad you kept repo option in deluge because that was the only thing I could install to that 256MB machine. Other deluge options were failed as well because they were requiring building as well.

> I worry your machine with 256MB doesn't have enough ram to run a torrent client at all.
No they run perfectly fine once they are installed, I'm using these low memory machines for low activity things so no problem regarding that. So if I could install rtorrent it would be perfectly fine for me but couldn't do that because couldn't compile it.

**Comment by liaralabs** [comment]
Added in 1bcda581977f0ed076034fa57bbbe453011458b4
