### ISSUE TITLE
Filebrowser install script should exit upon error

### ISSUE THREAD

**Issue by garikaib** [liaralabs/swizzin#231]
**Describe the bug**
I use an Arm64-4GB from Scaleway and like your script. I suspect Arm is not supported officially although the panel and using deluge repo works. Just for a kick I attempted to install filebrowser and while the script cheerfully says it has been installed after a few seconds I got a 502 error from Nginx.
A quick scan of the script shows why. Amd 64 is hardcoded in the script when downloading the filebrowser binary from its github repo. Upon extracting an initial execution is carried out to set things up. On arm64 the amd64 binary will fail.
**Suggestions**

1. During initial installation test to verify we are dealing with amd64 and issue warning here (as long as packages are being pulled from repos we probably won't run into issues but there is not guarantee)
2. In the filebrowser script line 34 change script and pull arm64 if we are on arm
3. Or on line 44 abort installation and warn user

**To Reproduce**
Steps to reproduce the behaviour:
1. Install package 'filebroswer.' on arm
2. Go to 'example.com/filebrowser'
3. Error '502'

**Expected behavior**
Filebrowser launches

**Server Info (please complete the following information):**
 - OS: Debian 10 Arm64

**Additional context**
Filebrowser will obviously not run so Nginx gets a connection refused error.

**Comment by liaralabs** [comment]
Thank you for the detailed report.

Unfortunately, I don't provide support for ARM64-based operating systems and will not be adding support for them in any of the installation scripts. As stated on the [docs homepage](https://docs.swizzin.ltd): a x86_64 processor is **required**. I simply don't have time to maintain and test an additional architecture at this time.

I'm happy to add a warning to the initial setup if it would help avoid confusion, because as you stated some things do work. The alternative to this is simply aborting the setup entirely, which I'd rather not do.

Regarding aborting packages on failure: many packages could `|| exit`  at potential failure points; however, it will require a more thorough eye than simply killing the script as many applications also require cleanup in the case of failure, thus your 3rd suggestion is welcome, though part of a larger issue that requires thought out logic and modifications to more than one script.
