### ISSUE TITLE
Server safety

### ISSUE THREAD

**Issue by internety1** [liaralabs/swizzin#237]
Do I need to add some special safety to server or script will do everything for me ?

**Comment by liaralabs** [comment]
I take care to make sure applications are well secured against potential remote attackers.

The most important aspects of keeping your server secure:

- Using strong passwords
- Even better: disable password authentication (use public/private key pairs)
- Keeping your server up-to-date (`apt update && apt upgrade`)

However, you can do more to secure your server, but these are personal preferences:

- Change your SSH port (arguable impact on security, anyone with a port scanner can determine your SSH port if you change it)
- Configure firewall rules (I don't do this due to the complex and random port needs of seedboxes)

**If you add secondary users to your seedbox, make sure you trust them. The publicly available version of this script has never been and will never be intended as a commercial solution for a multi-user environment as securing a box against users who already have ssh access is a completely different game.**

Binding applications to TCP ports is an inherently insecure practice (this is why I utilize unix sockets for rTorrent, which allow for fine grained permission control). Anyone with SSH access to a machine can tunnel to any port of an application that's been bound to `127.0.0.1`. This will bypass nginx basic authentication if the application does not have it's own form of auth enabled.

If you are worried about local users potentially accessing applications they shouldn't be, please consider enabling the "Forms" method of authentication in applications like Sonarr/Radarr. These auth methods will not conflict with the nginx basic authentication -- be aware that "basic" auth in any application **will** conflict and will likely result in a login dialog loop if you enable basic auth both in the application and have it enabled in nginx.
