### ISSUE TITLE
Fix Nginx 404 Errors due to proxy hash being exceeded

### ISSUE THREAD

**Issue by garikaib** [liaralabs/swizzin#240]
**Describe the bug**
If you install too many apps eventually you start getting 404 errors on some of them. Alternatively, you can see the following warning when you run nginx -t
`nginx-t
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size` 

**To Reproduce**
1. A number of packages. I have 12 including rutorrent and deluge
2. Go to 'example.com/service'
3. Error '404' not found

**Expected behavior**
We see the service running in browser.

**Server Info (please complete the following information):**
 - OS: 18.04.03
-CPU:Intel® Xeon E3 1240v6
-RAM:32GB
-Disk:500GB SSD

**Additional context**
Enabling ssh forwarding and visiting the related service on localhost:8181 for example shows the service is running.
**Suggested Fix**
Add the following lines to /etc/nginx/snippets/proxy.conf
`proxy_headers_hash_max_size 512;
proxy_headers_hash_bucket_size 128;` 
Reload nginx
systemctl reload nginx.service

**Comment by liaralabs** [comment]
This is a warning, not an outright error. In my experience, any warnings you may be receiving from nginx are typically not your culprit in causing 404 errors, but I could be wrong.

The warn message you sent over yourself states thus:
```
[warn] could not build optimal proxy_headers_hash ... ignoring proxy_headers_hash_bucket_size
```

The message makes it sounds as if nginx knows there's an issue but has ignored a parameter which allows it to continue.

I have never needed to set `proxy_headers_hash_max_size` or `proxy_headers_hash_bucket_size` even on a server handling north of 200 reverse proxies and have never had any individual complain of a 404 error on their proxy.

If the warning message concerns you, I believe I have fixed it by nixing headers which were set twice in jackett (once in jackett.conf and again in the proxy snippets). I'd recommend giving your server  a `box update` before wandering down this road further.

Otherwise, please list all the apps you have installed and I'll see if I can reproduce the issue. However, like I said, on a sever with 200+ proxies confs spanning 12 app configs (+ruTorrent), I have never seen a 404 issue arise (even with the duplicate headers and warning in place).

**Comment by garikaib** [comment]
Mmmm. I am not sure what's going on here. I just tested again using Debian after the fix you suggested. I couldn't access example.com/sonarr and was getting 404 errors. The two lines fixed the issue! I am hardly a Nginx expert though so I don't know how this is all happening.

**Comment by liaralabs** [comment]
So, is the issue fixed for you then? If so, please close :slightly_smiling_face:
