### ISSUE TITLE
Deluge 502 bad gateway

### ISSUE THREAD

**Issue by naderkasri** [liaralabs/swizzin#243]
Hey there,

I just installed Swizzin (which is fantastic) on another new server.
However, I'm facing issues with Deluge. It's probably installed, enabled and on.
When I try to access it with my-ip/deluge/ I have a 502 bad gateway.

I tried installing multiple versions of Deluge (currently 2.0 repo) through box install, but to no avail.

Looking forward to your help!

Thanks :)

**Comment by liaralabs** [comment]
2.0 repo is not an option in my installer (there is no distribution currently pushing Deluge 2.0 in their official repositories and I don't use PPAs), so I'm confused as to what you're actually doing.

I just tested a fresh install on Debian 10 and could not reproduce your issue with Deluge 2.0 and RC_1_2 for libtorrent.

If you could please provide more information (i.e. the information requested in the default issue template):

- OS
- Steps to reproduce (e.g. which options did you choose during the installer?)

Have you done any sort of troubleshooting? (e.g. Is deluge-web currently running? `sudo systemctl status deluge-web@<username>`)

**Comment by naderkasri** [comment]
Thanks for answering!

I forgot which version I unstalled, but it didn't work, so I uninstalled it.
When installing Deluge 2.0 and RC_1_2 for libtorrent, on Debian 9.4 Stretch, I get the following issue:

```
Building Deluge
/etc/swizzin/sources/functions/deluge: ligne 259 : cd: deluge: No such file or directory. 
fatal: Neither this or any of its parents are a git repo : .git
dpkg: error: cannot access archive '/root/dist/deluge-common_.deb': No such file or directory. 
deluge-common is now on (« hold »).
Configuring Deluge
/etc/swizzin/sources/functions/deluge: ligne 321: deluged : no such command
chown: Cannot access '/home/raynz/.config/deluge/plugins/ltConfig-.egg'                                                                                                             : No such file or directory. 
/usr/local/bin/swizzin/install/deluge.sh: ligne 165: deluged : command not found                                                                                                           ble
/usr/local/bin/swizzin/install/deluge.sh: ligne 201: deluged : command not found
```

**Comment by liaralabs** [comment]
I just tested this on a Stretch VM and didn't have any issues there either.

I wonder if there may have been a temporary outage on the Deluge git repo when you attempted your checkout

```
/etc/swizzin/sources/functions/deluge: ligne 259 : cd: deluge: No such file or directory. 
```

Indicates that the git clone command failed. Considering you have swizzin installed and swizzin utilizes git during the setup, I'm going to go ahead and assume you have git installed.

Do you happen to have the install log (`/root/logs/install.log`)? The output of the git command would have been piped there if you attempted to setup deluge during your initial setup. Otherwise, have you attempted to reinstall Deluge since?

**Comment by naderkasri** [comment]
Thanks for answering!

I have tried to reinstall Deluge once again, without any success.
I get the same error.

In the install.log file, when searching for deluge, I only have
```
 Cloning in 'deluge'...
Created symlink /etc/systemd/system/multi-user.target.wants/deluged@raynz.service → /etc/systemd/system/deluged@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/deluge-web@raynz.service → /etc/systemd/system/deluge-web@.service.
```

**Comment by liaralabs** [comment]
Is your server up-to-date? You mentioned you're running Debian 9.4 (and 9.10 is the latest snapshot).

Furthermore, you mentioned it was a new server, but it's worth checking: swizzin is up-to-date as well?

To be clear, you receive the same error as before?

```
/etc/swizzin/sources/functions/deluge: ligne 259 : cd: deluge: No such file or directory. 
```

Are you able to help the installer along by checking out deluge beforehand?

```
cd /tmp
git clone -b master git://deluge-torrent.org/deluge.git
```

And then run the installer or upgrade?

**Comment by naderkasri** [comment]
The server is new and I've installed Debian 9.4 on it. I have another server with Debian 9.4 and Deluge works fine (via swizzin).

However, I'm able to properly git clone deluge on my other server, but I have an error when doing it on my new server.

```
fatal: unable to connect to deluge-torrent.org:
deluge-torrent.org[0: 140.211.166.20]: errno=Connection timeout
```

**Comment by liaralabs** [comment]
Bleh, I referenced the wrong issue # in my commit, see: ced724babbc767816f17ea78f67f4361301aa8d4

This adds github as a backup source for Deluge if deluge-torrent.org is failing (I don't know why it would be, this is a local issue --perhaps the IP of your new server has made it onto a blacklist). Can you please test and see if Deluge will checkout and compile now?

**Comment by naderkasri** [comment]
Thanks for answering!

I updated swizzin and tried to install Deluge.
However, I still have errors (my system is in French but I'll translate the important stuff):

```
ERROR: Cloning Deluge from deluge-torrent.org failed, attempting github backup.
(Lecture de la base de données... 113402 fichiers et répertoires déjà installés.)
Preparing to depackage .../dist/deluge-common_2.0.3.deb ...
Depackaging deluge-common (2.0.3) sur (1.3.13+git20161130.48cedf63-3) ...
dpkg: error treating the archive /root/dist/deluge-common_2.0.3.deb (--install) :
tempting to replace « /usr/share/icons/hicolor/48x48/apps/deluge.png », that also belongs to the package deluge-gtk 1.3.13+git20161130.48cedf63-3
dpkg-deb: error: the sub-process paste was killed by the signal (broken relay(pipe))
Traitement des actions différées (« triggers ») pour man-db (2.7.6.1-2) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.15-1) ...
Errors during the execution :
 /root/dist/deluge-common_2.0.3.deb
deluge-common is now frozen (« hold »).
Configuring Deluge
/etc/swizzin/sources/functions/deluge: ligne 321: deluged : no such command

```

**Comment by liaralabs** [comment]
The error you're seeing is actually expected if you've installed Deluge outside of swizzin through apt:

```
dpkg: error treating the archive /root/dist/deluge-common_2.0.3.deb (--install) :
tempting to replace « /usr/share/icons/hicolor/48x48/apps/deluge.png », that also belongs to the package deluge-gtk 1.3.13+git20161130.48cedf63-3
```

What I call `deluge-common` is actually several packages according to Ubuntu/Debian: `deluge`, `deluged`, `deluge-web`, and `deluge-console`. I lump them into one package because there's not much need to separate them out for our install purposes.

Thus, there are package conflicts because this `deluge-common` is trying to overwrite files owned by `deluge-gtk` and `deluge-gtk` isn't necessarily being replaced by this package upgrade.

If you successfully configured Deluge (i.e. `/install/.deluge.lock` exists) then `box remove deluge` should clean all traces of *any* install method. (`apt purge deluge*` should catch `deluge-gtk` even though `deluge-gtk` is not a part of the repo install).

Otherwise, if you're still having issues even after `box remove deluge`, you may need to comb through your packages yourself to see if there are any other Deluge packages that may be conflicting:

`dpkg -l | grep -i deluge`

If they are there, you should remove them to provide a fresh slate for my version of `deluge-common` to install into.

**Comment by naderkasri** [comment]
Hey!

I did a `box remove deluge` as well as a `apt purge deluge*` which actually removed `deluge-gtk`
Then, I did a fresh install using `box install deluge` (Deluge 2.0 then 1.2 RC libtorrent something).
I still have an error :
```
Building Deluge
ERROR: Cloning Deluge from deluge-torrent.org failed, attempting github backup.
Selecting package deluge-common that was previously not selected.
(Lecture de la base de données... 112606 fichiers et répertoires déjà installés.)
Preparing to depackage.../dist/deluge-common_2.0.3.deb ...
Depackaging deluge-common (2.0.3) ...
Configuring deluge-common (2.0.3) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.6.1-2) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.15-1) ...
deluge-common is now frozen (« hold »).
Configuring Deluge
```
Thanks so much for your help, I really appreciate it!

**Comment by liaralabs** [comment]
As long as Deluge is running, you can ignore that error. If it's confusing I can change the wording to `NOTICE` or `WARN`. I don't see any other errors that indicate a problem otherwise.

The real error will kick in if it can't clone from either repository and the script should exit without finishing if that's the case.

**Comment by naderkasri** [comment]
The problem is that I still have a 502 Bad gateway.

`systemctl status deluge-web@<username>` returns `[ERROR   ][deluge.ui.web.json_api     :438 ] Unable to connect to daemon, check host_id...` even though it says `active `in green

**Comment by liaralabs** [comment]
That error is probably a red herring. You shouldn't be getting a 502 error if everything is currently running. 

If you previously had your own version of deluge running, the web port proxied may be different from the web port being used.

If you haven't made any customizations try giving `box upgrade nginx` a run. It should reset and redo your configs for all your proxied apps

**Comment by naderkasri** [comment]
`box upgrade nginx` didn't help, unfortunately.

The web ports in both files match :(

**Comment by liaralabs** [comment]
Any clues in `/var/log/nginx/error.log`?

**Comment by naderkasri** [comment]
In that file, I have the following error:

`connect() failed (111: Connection refused) while connecting to upstream request: "GET /deluge/ HTTP/1.1`

Other than that, nothing much :/

**Comment by naderkasri** [comment]
I did a fresh Debian 9.4 install and reinstalled swizzin. Deluge now works!
Thanks again :)
