### ISSUE TITLE
Sonarr can take a very long time to install due to issues with mono

### ISSUE THREAD

**Issue by garikaib** [liaralabs/swizzin#245]
**Describe the bug**
When installing sonarr the script echos text saying Sonarr installation can take up to 2 minutes. It can take a long time on Debian 9

**To Reproduce**
1. Install package 'sonarr' on Debian 9 with a modest processor e.g. Atom
2. Go to 'terminal'
3. Error 'it seems like the process gets stuck while installing'

**Expected behaviour**
Installation completes in the said 2 minutes
**Server Info (please complete the following information):**
 - OS: Debian 9
-Hardware:Intel Atom C2350, Ram 4GB

**Additional context**
It seems there is an issue with compiling mono on Debian 9 https://github.com/mono/mono/issues/11690 to be on the safe side warn users that this can take hours!

**Comment by userdocs** [comment]
Is there a rant tag for issues?

As far as i am aware it does not compile from source but i do think there are some elements compiled during installation increasing the time taken to install. 

Either way it is not a quick process on any platform but using an atom in general should require a more generic disclaimer. Perhaps when attempting to install swizzin.

**Comment by liaralabs** [comment]
As userdocs already mentioned, this isn't something I have any control over. We are installing packages from apt -- if they have their own compile-like options built into their post-install scripts then it will take however long it takes. Furthermore, the mono ecosystem is roughly 160 packages all on its own, which takes its own time (often from a 3rd party mirror which isn't decentralized like the majority of official repositories).

I have stated in the docs that I don't recommend using swizzin on anything less than an atom c2750 (even then, it can still take a **long** time). Deluge compiles can take 25 minutes on a single core VPS. A 2 core atom vps has less than 1000 passmarks, which might even be less than certain single core VPSs.

I don't know what else to say other than to potentially remove any mention of ETAs from the installer because ETAs will vary depending on the task and the resources at hand for that task (i.e. cpu for compilation tasks, available io/net speed for apt tasks)

**Comment by garikaib** [comment]
Thank you for the response. I understand, adding a disclaimer is is actually fine. Something like this will take 2 minutes or a longtime depending on your processor. To be honest on my primary box with a Xeon processor and 32 GB RAM it takes less than 20 seconds so i had never experienced this. It didn't take me long to see whay the issue was once I attempted the steps manually.

Often times developers are working on good powered machines so they might miss quirks like this. I just wanted it document it in case someone encounters the same issue and are wondering.

Atom is light weight as you have pointed out. Works great if you remove transcoding though.
