### ISSUE TITLE
bazarr give 502 Bad Gateway error

### ISSUE THREAD

**Issue by whoamikyo** [liaralabs/swizzin#253]
**Describe the bug**

when open bazarr gives bad gateway error

**To Reproduce**

1.just did a fresh debian 9 install and installing swizzin

**Server Info (please complete the following information):**
 - OS: 

Linux RKZ-6 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

and

Linux RKZ-5 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

My /var/log/nginx/error.log

[error.log](https://github.com/liaralabs/swizzin/files/3747871/error.log)

**Comment by liaralabs** [comment]
I cannot replicate this issue on a fresh installation using Debian 9

Per your log file:

```
connect() failed (111: Connection refused) while connecting to upstream, client: MyIP, server: MyServerName, request: "GET /bazarr HTTP/1.1", upstream: "http://127.0.0.1:6767/bazarr", host: "MyServerName"
```

Connection refused points to the possibility that bazarr isn't currently started.

This can be verified with `systemctl status bazarr`

**Comment by 98h398hrpohpoai** [comment]
Ran into this issue was well. 
Pretty sure the base url wasn't specified during initial setup.
I don't remember if it was originally there or I deleted it during the initial setup, but was unable to access bazarr after completing the initial setup (gateway error upon reloading).
Was able to regain access via nginx reverse proxy to the port without base url.

**Comment by rflaperuta** [comment]
Ran into something similar today.
 
Turns out Bazarr needed Python 3.7+, but the default on my Ubuntu 18.04 was Python 3.6.9. 

To find the error message, you can log into the machine as the user bazarr runs on.
Change into its directory, usually `/home/<username>/bazarr`, and run `python3 bazarr.py`

1- Decided to install asdf-vm (Runtime Manager) (follow instructions on site then restart the shell after)
2- Installed all dependencies to build python from source. [the first 5 sudo apt instructions from here](https://solarianprogrammer.com/2017/06/30/building-python-ubuntu-wsl-debian/)
3- Using asdf-vm installed Python 3.7.7 (It is compiled from source, thus the need to check for dependencies first)
4- Configured for my linux user which python to use `asdf global python 3.7.7`
5- Found where is my new python version `which python3`
6- As `root` edited bazarr.service and changed the system python to mine (Found on step 5)
7- Did a `systemctl daemon-reload`
8- Then `systemctl restart bazarr`

From now, you should be able to connect to bazarr from the `panel`.

**Comment by liaralabs** [comment]
This is a less than ideal situation considering that the author of Bazarr has essentially forced upgrades to Python3.7 and is not supporting any long-term operating systems which are still well within their support windows and stuck on versions 3.5 and 3.6.

In a word: Grr.

I'm not really willing to push global updates to Python for OS's like Stretch and Bionic as there's no telling what may happen to things like Deluge v2 or other python-based packages if you already have them installed and I'd like to keep the OS packages in tact.

I will need to look into setting up a venv specifically with a non-standard version of Python.

**Comment by liaralabs** [comment]
I have just pushed a fix which should solve all the issues associated with bazarr that are known to me right now.

There is an update script, as well if your current install is currently broken.

Please re-open a new issue with new details if there are still issues.

**Comment by coldeny** [comment]
Hello. I am using debian 12 and I am currently experiencing this issue. I checked status and bazarr is "active (running)" somehow. The python here is 3.11.2 too. I don't get what's wrong. I tried reinstalling. I also have radarr, plex and jackett. Only bazarr is down. Panel shows Bazarr as green.

**Comment by liaralabs** [comment]
Please re-open a new issue and provide the requested information. Your issue is different from the reason that this issue was opened for and fresh information needs to be provided
