### ISSUE TITLE
Box update command issue

### ISSUE THREAD

**Issue by an0n666** [liaralabs/swizzin#264]
**Describe the bug**

When box update is invoked, all services get restarted. Even if a user had his service turned off, the service will start regardless.

**To Reproduce**

Enter box update cmd

**Expected behavior**

Merely updating the scripts shouldn't restart the services or start it for users who had the services disabled.

**Server Info:**
Ubuntu 18.04 LTS

**Comment by liaralabs** [comment]
The reason you're seeing this is because `box update` doesn't just run a `git pull` -- it runs scripts for updates that fix bugs and keeps swizzin up to date with any changes that could be potentially breaking.

That said, "all the services" shouldn't be restarting every time you run update. Most of the commands will only ever fire a single time and if there was a restart command in there that wasn't prefaced by checking to see whether or not the service was running before running the update scripts, then yes a few applications could be restarting that you had stopped.

I've gone through the majority of the update/upgrade scripts and have dealt with most of them -- there shouldn't really be anything starting that wasn't started already before running the script now.

However, if you are still facing the issue, then I would absolutely invite you to give me more info regarding **which services in particular** you are talking about.

Related commit: 37a15c2

**Comment by an0n666** [comment]
I understand that some services may require restarting if you change some configuration. But if you just changed let's say the upgrade script for deluge, and I do not have it installed...then why should rtorrent get restarted as well whereas no change was made to it's config? The script should check whether or not some change was included for the particular service before restarting it.

**Comment by liaralabs** [comment]
As I stated in the previous reply I had taken steps to mitigate the restarting of applications.

Previously, the scenario you are describing should not have been happening regardless.

Despite this, following the commit, if you are still having issues with specific applications please tell me which applications specifically seem to be affected. Made up examples and generalities do not help me debug issues. If you have an issue, please convey what *exactly* the issue is.

If I do not see a response to this in a few days, I will assume the problem was fixed in the previous update and this issue is able to be closed.

**Comment by an0n666** [comment]
I was having issues with rtorrent.

**Comment by liaralabs** [comment]
The command for rtorrent changed from

```
systemctl restart rtorrent@${user}
```
to
```
systemctl try-restart rtorrent@${user}
```

`try-restart` should only restart the application if it was previously running and it will do nothing otherwise. If you do find any future problems in the same vein, feel free to re-open.
