### ISSUE TITLE
Cant connect to Jellyfin in the default port

### ISSUE THREAD

**Issue by nygage** [liaralabs/swizzin#279]
**Describe the bug**
I have installed Jellyfin using the comand "box install jellyfin" after that, I can connect to it by web, but if i try to connect using the port with https, i cant connect.
Example:
http port: 21857 in my app i put: myip:21857/jellyfin and it works
https port: 25806 in my app i put myip:25806/jellylfin not works, i put https://myip:25806/jellyfin, nothing.

What can i do?

One more thing, i have to change in the settings this "Bind to local network address:" to 0.0.0.0 because by default it says 127.0.0.0 and it not connect.

Thanks

**Expected behavior**
Connect to the server

**Server Info (please complete the following information):**
 - OS: Ubuntu 18.04
- Web server: nginx
![image](https://user-images.githubusercontent.com/36328659/78730822-37d72000-793e-11ea-997f-69291920f76c.png)

Thanks

**Comment by liaralabs** [comment]
userdocs would have a better understanding of the script since it's his contribution; however, from my perspective, you're digging too far into it.

When nginx is installed, we disable remote access directly to the port and you connect only through the reverse proxy. Thus, if you are binding back to 0.0.0.0 you are changing the intended function of the reverse proxy. This is not a major deal since jellyfin uses its own authentication.

That said, you shouldn't be connecting to the ports itself, you should be connecting to:

`https://ip/domain.com/jellyfin`

Over port 443

**Comment by nygage** [comment]
@liaralabs so i have to configure the reverse proxy to point to that ports? or the script configure it by itself?
Thanks

**Comment by nygage** [comment]
Solved, terrible easy configure let's encrypt in swizzin, thanks for your help and your patience!
