### ISSUE TITLE
Quota install fails

### ISSUE THREAD

**Issue by tfp1** [liaralabs/swizzin#29]
With either option selected, shell response is:
`ERROR: Could not find a hook in /etc/fstab for quotas to install to. Quota requires either defaults or errors=remount-ro to be present as a mount option for the intended quota partition.`

**Comment by liaralabs** [comment]
Can you paste your /etc/fstab?

The quota installer works by matching against `errors=remount-ro` or `defaults`, if it can't match a pattern it won't bother to insert; otherwise the function could become somewhat destructive. The behavior your seeing is currently working as intended and I'm assuming that you have a non-standard fstab or you are potentially running the installer under a VPS.

**Comment by tfp1** [comment]
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/sda3       /       ext4    errors=remount-ro,relatime      0       1
/dev/sda2       /boot   ext4    errors=remount-ro,relatime      0       1
/dev/sda4       /home   ext4    defaults,relatime       1       2
/dev/sda5       swap    swap    defaults        0       0
proc            /proc   proc    defaults                0       0
sysfs           /sys    sysfs   defaults                0       0
devtmpfs        /dev    devtmpfs        rw      0       0

**Comment by liaralabs** [comment]
The match was failing because the installer was looking for a space to separate the columns rather than a tab. This latest commit searches for both a space and a tab and attempts to match against both. This should rectify the error you saw here.
