### ISSUE TITLE
Transmission PPA for Focal Fossa 404's

### ISSUE THREAD

**Issue by flying-sausages** [liaralabs/swizzin#314]
**Describe the bug**
When doing an apt update, the transmision PPA 404's

**To Reproduce**
1. Install Transmission
2. run `sudo apt update`

**Expected behavior**
A siccesful update with transmission packages being retrieved from the PPA instead of the Ubuntu repos

**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
```
E: The repository 'http://ppa.launchpad.net/transmissionbt/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

https://github.com/transmission/transmission/issues/1197

**Comment by liaralabs** [comment]
I don't think the transmission team maintains the PPA:

https://github.com/transmission/transmission/issues/521

Furthermore, I'm guessing no PPA exists because the version in Ubuntu 20.04 is already the latest, so building a 3rd party package is superfluous. Similarly, there doesn't appear to be a PPA package for disco or eoan release, where the version is also already at 2.94. Thus, the PPA should be disabled for focal unless/until there is an update from transmission which would then trigger an updated package.
