### ISSUE TITLE
Issue in rtorrent service script

### ISSUE THREAD

**Issue by an0n666** [liaralabs/swizzin#322]
**Describe the bug**

rtorrent process is not force closed before starting new rtorrent process.
Sometimes when you restart rtorrent, the old process hangs and doesn't get killed.
But a new process is spawned along side old process.

**To Reproduce**

1. Install package - rtorrent 0.9.8
2. Go to panel -> restart rtorrent service
3. Error -> two processes are spawned if previous one gets hanged or takes time to exit.

**Expected behavior**

Previous process should be force killed before starting new one.

To do that simply add:
ExecStartPre=-/usr/bin/killall --user %I -w -s 9 /usr/bin/rtorrent

also after stopping the service allow rtorrent process to exit.
To do so simply add:
ExecStopPost=/bin/sleep 10

**Server Info (please complete the following information):**
 - OS: [e.g. Debian 10]
Ubuntu 18.04

**Comment by flying-sausages** [comment]
I suppose this is more of a swizzin panel issue then swizzin core? In normal CLI environments, systemctl grabs the terminal until the service is down

**Comment by an0n666** [comment]
I don’t think so. If you send restart command to systemctl it’ll just execute the ExecStop and start the new process. It doesn’t wait for process to end. The script has shortcomings.

**Comment by an0n666** [comment]
I’ve updated the OP. The issue was mainly in the restart option.

**Comment by flying-sausages** [comment]
Is this reproducible with 0.9.6? Can you try `box upgrade rtorrent` and choose that version? After all, it is the latest "stable" version, while 0.9.8 is not.

**Comment by an0n666** [comment]
0.9.6 is not stable. There’s a lot of crashing issues on 0.9.6 and on latest ones as well.  Anyways, the issue here is regarding the limitations of the rtorrent systemd script created by swizzin. 

In rtorrent config file swizzing enables random ports by default. And on start or restart, the systemd script removes the pid lock file. This allows two rtorrent processes to spawn if previous one didn’t get killed properly for some reason. But If rtorrent was set to a static port a 2nd process would’ve failed to bind the listen sockets and crashed. So this multiple instances running for same user happens due to random port + systemd scripts failure to close any running processes before restarting.  

I’ve already described in my post the remedy to this problem. You force kill any running processes before starting a new one.

Currently I’m using this:

[Unit]
Description=rTorrent
After=network.target
[Service]
Type=forking
KillMode=process
User=%I
ExecStartPre=-/usr/bin/killall --user %I -w -s 9 /usr/bin/rtorrent
ExecStartPre=-/bin/rm -f /home/%I/.sessions/rtorrent.lock
ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent
ExecStop=/usr/bin/screen -X -S rtorrent quit
ExecStopPost=/bin/sleep 10
WorkingDirectory=/home/%I/
RemainAfterExit=no
Restart=on-failure
RestartSec=5s
[Install]
WantedBy=multi-user.target

**Comment by flying-sausages** [comment]
Hey, there's a reason I put quotes around stable ;) I'm just saying that [that's what the maintainers of rtorrent say](https://github.com/rakshasa/rtorrent/#stable). Reason I asked is because we have only seen this being an issue with people who installed 0.9.8, so we're curious if it is a coincidence or not.

It might after all be an issue in how 0.9.8 handles termination compared to 0.9.6.

There definitely seems to be an issue with the way 0.9.8, swizzin and the panel work with each other, and you do indeed provide a fix to the issue presented when using 0.9.8. The thing is there were talks of pinning the rtorrent version at what the authors deem as stable within the swizzin install script and allowing optional upgrades above that through the current upgrade method, or renaming them/appending them with "stable" and "unstable" in the whiptails.

If the issue is reproducible with 0.9.6, then there is no reason to not implement your proposal, and a PR should be created by either you or someone else. I just don't have means to test this for the forseeable future. Otherwise, we think it is a valid choice to make the choice of what versions swizzin will offer on a sliver plate and which ones not (maybe a bronze plate).

**Comment by an0n666** [comment]
I had same issue with rtorrent 0.9.6 and then moved on to 0.9.8 only to rediscover the exact same issue. 
I had some seedboxes where clients would restart rtorrent and later complained about high cpu usage. Later I found there were two pids of rtorrent running. One of them had failed to exit when restart was called. Probably some thread hanged during exit. I didn’t have the time or enthusiasm to investigate further and implemented my own patch. Just thought about letting the maintainer know that a improvement is possible to take care of such cases(regardless of version or stability).

**Comment by flying-sausages** [comment]
Mmmm alright gotcha, cheers. Did you try running 0.9.8 using [systemd directly without screen](https://github.com/rakshasa/rtorrent/wiki/Daemon_Mode) by the way? It removes the user interface so I'm no if that's in line with your use-cases but I wonder if it introduces any behavioural changes that would be a mitigation of the above.

**Comment by flying-sausages** [comment]
Also, just to verify, you're on `Screen version 4.06.02 (GNU) 23-Oct-17` right?

**Comment by an0n666** [comment]
> Mmmm alright gotcha, cheers. Did you try running 0.9.8 using [systemd directly without screen](https://github.com/rakshasa/rtorrent/wiki/Daemon_Mode) by the way? It removes the user interface so I'm no if that's in line with your use-cases but I wonder if it introduces any behavioural changes that would be a mitigation of the above.

No I haven’t tried that. I’ll give it a try and see how that goes. For what I’ve noticed is the screen session gets terminated but rtorrent pid continues to run. It doesn’t stop on SIGTERM. I’ve to use -9.
