### ISSUE TITLE
cant create letsencrypt

### ISSUE THREAD

**Issue by poentodewo** [liaralabs/swizzin#37]
i have 2 hetzner servers 1 is oke and the second server fail
can u fix ? thx
i try with another script rtinst arakashi just fine but i like ur script :)
![screenshot_2017-11-04_23-07-58](https://user-images.githubusercontent.com/15877677/32407071-cda451d6-c1b5-11e7-900f-b3eee272ff1a.png)

**Comment by liaralabs** [comment]
Error messages can often be quite helpful :)

In your case: Sign failed, too many certificates already issued for your-server.de

Since this is the default hetzner domain, this is not surprising. I would recommend using your own domain to get around this.

More info on this error: https://community.letsencrypt.org/t/too-many-certificates-already-issued-for-domain/28778
