### ISSUE TITLE
Massive nginx log size

### ISSUE THREAD

**Issue by Evoley** [liaralabs/swizzin#41]
I installed swizzin about a month and I'm looking at over 1 GB of nothing but access and error logs. This is sort of ridiculous. All I'm seeing is just all over again. 
000.000.000.000 - thotbot [18/Nov/2017:06:25:05 +0100] "GET /rutorrent/plugins/autodl-irssi/getlines.php?cid=664418131&_=1510981923386 HTTP/1.1" 200 52 "https://winers.club/rutorrent/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.52 Safari/537.36"

**Comment by liaralabs** [comment]
I don't do anything to alter log levels in nginx or php7.0-fpm. The logging will be done according to the log level defined in your php.ini and nginx.conf.

Access logs and error logs will contain different information. Information is written to the access log when a client makes a request -- in this case the request is for a php file contained by the autodl plugin. I would be surprised if your error.log contained similar information.

An access request might be written each and every time the ruTorrent interface refreshes -- if you have decreased the refresh time of the ruTorrent interface, this might cause the access log to increase at a higher rate. Meanwhile, error logging will be done according to the log level defined (error, debug, warn, etc).

The QuickBox panel itself throws many php warnings, which might be cause for increased log size, especially if you leave a tab running with the QB Panel open (as the panel itself refreshes constantly via ajax). This is a known issue with the panel. As someone who doesn't really dabble in php, it will most likely stay this way unless it is fixed with the maintainer upstream.

Some more reading:

https://www.keycdn.com/support/nginx-error-log/

Or perhaps you might want to disable logging entirely?

https://www.digitalocean.com/community/tutorials/how-to-configure-logging-and-log-rotation-in-nginx-on-an-ubuntu-vps

Also, debug logs can grow very very rapidly, ensure you have not accidentally left debug logging enabled for your error logging.

My own log folder is 54mb and has nothing beyond November, so I think there might be some specific circumstances on your server that are contributing to your log bloat. (Maybe log rotate or some of the other things mentioned above)

**Comment by liaralabs** [comment]
As there has been no further discussion on this issue, I am closing it.

If you wish to contribute further, feel free to re-open.
