### ISSUE TITLE
net-tools missing

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [liaralabs/swizzin#412]
## Bug description
Fresh install of Ubuntu and running
sudo -H su -c 'bash <(wget -O- -q https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)'
resulted in error when installing wireguard
/usr/local/bin/swizzin/install/wireguard.sh: line 169: route: command not found
Apt install complete
Configuring Wireguard for tstuart  |  Configuration failed

## Reproduction steps
1. Install Ubuntu 20.04.1 LTS
2. run apt update && apt upgrade
3. Run sudo -H su -c 'bash <(wget -O- -q https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)'
4. select wireguard
3. Error /usr/local/bin/swizzin/install/wireguard.sh: line 169: route: command not found - happens when it's supposed to identify your adapter

## Installed applications through swizzin
Nginx, panel, deluge,wireguard

## Expected behavior
No error should display, instead it should show the proper network adapter, when install is completed it should then reflect the configuration

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Image Source: ISO

## Is Swizzin up to date?
HEAD is now at f93b6da

## Additional context
sudo apt install net-tools fixes this. Since this doesn't appear to have been part of the base install of ubuntu it should be a dependant on package...

**Comment by liaralabs** [comment]
This package does indeed appear for me in a minimal Hetzner install and it is present on every one of my Debian servers without specifically installing it, so this is why it has not been included. If I run my tests and no apt packages are needed, they won't typically get added.

If you tested an ISO server install, it's been a while since I tested one of those and the minimal image may indeed not ship with net-tools.

I've just pushed net-tools as a global depend -- for users facing this problem, run `box update` first and `net-tools` will be installed.
