### ISSUE TITLE
wireguard needs ln of resolvctl

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [liaralabs/swizzin#414]
## Bug description
After installing wireguard, and building the interface wg0 using the settings for my VPN provider I tried to bring the connection up and it says 
/usr/bin/wg-quick: line 32: resolvconf: command not found

## Reproduction steps
1. Install package 'wireguard'
2. Go to 'sudo wg-quick up wg0'
3. Error '/usr/bin/wg-quick: line 32: resolvconf: command not found'

## Installed applications through swizzin
wireguard,jackett,sonarr,radarr,

## Expected behavior
It should connect to VPN after doing up command

Easily fixed with sudo ln -s /usr/bin/resolvectl /usr/local/bin/resolvconf

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Image Source: ubuntu-20.04.1-live-server-amd64.iso

## Is Swizzin up to date?
HEAD is now at 840a462

## Additional context

 ```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.128.85/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
/usr/bin/wg-quick: line 32: resolvconf: command not found
[#] ip link delete dev wg0

 ... logs ...
 ```

**Comment by liaralabs** [comment]
I'm a bit mixed on this as wireguard has never intended to be used as a client on the swizzin end of the server.

The reason this problem crops up with your config but not with the standard swizzin-created entries is that you are specifying a DNS line, which wireguard attempts to change once connected to the tunnel. In swizzin-created entries, we are the tunnel, thus changing DNS is not required.

In my experience, the fix you provided will not actually solve the issue here (protecting against DNS leak) but will simply make the error go away and allow the interface to come up. Have you attempted a DNS leak test with the change you are proposing and can verify that the server's DNS entries are updated properly?

Otherwise, the `openresolv` package looks to be available in both Debian and Ubuntu and should also provide the missing resolvconf dependency -- this is the official suggested package to use in pair with wireguard (as per Debian -- Ubuntu suggests nothing and leaves the dependency completely unresolved).

**Comment by Bishop-trevorstuart** [comment]
I see what you're saying. I was/am using any VPN as a client not a server at all. 
I removed the ln created and installed openrsolv as suggested. Error is still gone, and with that being the better method it's what I'll use going forward.
