### ISSUE TITLE
All users: ~/.bashrc does not exist

### ISSUE THREAD

**Issue by nwcmn** [liaralabs/swizzin#45]
The file is copied as .bashrc.bak - not 100% sure if this is intended or not, but figured I'd put this out there as well. If intended, please ignore/close.

https://github.com/liaralabs/swizzin/blob/6f769d65e3d731424c2c71403adeef488d939669/setup.sh#L56-L59

**Comment by liaralabs** [comment]
This is actually intentional. The .bashrc used here (and in QuickBox) is actually from the original Swizards installation script. Unfortunately, there is a newline bug in the DF.sh script that causes issues when wrapping to newlines when the terminal size is not default, despite the fact that all the color codes are exited correctly (which is the source of issues like these).

This issue drives me crazy. As such, I opted to not overwrite .bashrc with a buggy one and left the old one in (inactive) as a bit of an easter egg for those who would prefer to use it. I don't particularly need a fancy bash shell, and there aren't really any useful aliases in the file. If you want the old Swizards style .bashrc, you're welcome to remove the .bak extension and reload your shell.
