### ISSUE TITLE
rTorrent vulnerability?

### ISSUE THREAD

**Issue by dwinnert** [liaralabs/swizzin#64]
Do I have to worry about this on my Swizzin install?

https://f5.com/labs/articles/threat-intelligence/malware/rtorrent-client-exploited-in-the-wild-to-deploy-monero-crypto-miner

Thanks!

**Comment by liaralabs** [comment]
I explained this in IRC, but I'll leave this here too.

Short answer: no, not from remote attackers.

RPC is properly configured -- for that article to call this an exploit is a bit click-baity as I don't specifically see anything wrong with either ruTorrent or rTorrent's implementation. They are fine, they just need to be configured properly. An exploit implies that even when things are configured properly, a vulnerability still exists.

So, why is this not a problem for swizzin? The RPC layer is secured and the port is not directly accessible externally:

1. The scgi port is bound to 127.0.0.1. The port itself is not exposed beyond the local machine.
2. The only way the port itself is exposed is through the scgi config in nginx. This mount point is password protected and accessible only by the user who owns it.
3. swizzin doesn't use the endpoint /RPC2, we use the username. The attacker would have to know the username of someone on the box to attempt to even try to start looking for RPC vulnerabilities. The attacker can't use an endpoint they don't know exists. RPC2 is the most common endpoint for ruTorrent, thus it can be scripted; however, since we configure it in a custom way, an attacker can't know easily which endpoint to start at unless they already know for certain that a username exists and has r(u)Torrent configured.

I suppose it is possible that on a machine with several users, the scgi port could be gathered from another user's rtorrent.rc and you could push commands from localhost to their rtorrent instance -- this would give you the ability to run commands as another user. However, in the case of swizzin, this isn't a major issue since I don't push NOPASSWD in sudo by default, thus local users can't go about executing sudo commands when they shouldn't be.

That said, I'll patch up permissions for home directories in the upcoming merge, as home directories aren't currently locked down (I tend to assume that extra users are trusted users and this is not being used in an untrusted setup). Further, I'll restrict the rtorrent.rc to be readable by user only -- this should take care of most of that potential vector. However, a potential bad actor could still use nmap to map open ports on localhost; however, I do not install nmap as part of swizzin and such a user would need sudo access to install it if the administrator of the server hasn't.

Unix sockets would take care of most of these concerns, but I'm worried about graceful updates to currently installed servers at this point. I'll look into altering the method, but there's no guarantee I'll make the switch.

**Comment by attritionorg** [comment]
@liaralabs re: "An exploit implies that even when things are configured properly, a vulnerability still exists." If the default configuration of rTorrent leaves the software open to abuse (e.g. the ability to co-opt it and install a crytpominer), that would still be considered a vulnerability by many. I think the key here is not just "properly configured", rather what is the default configuration. If I install rTorrent as a new user and don't read the documentation, would my installation be vulnerable in that context?

**Comment by liaralabs** [comment]
No, because rTorrent does not ship with XML RPC enabled by default, the user must enable it manually during compile.

In regards to default configuration, you can find the developer's defaults [here](https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent.rc). Notice how `network.scgi.open_port` is not included in this config and every option that is included is commented out with the instructions to enable only what you need. In regards to installing rTorrent from package management, not even Ubuntu or Debian push a config when installing it via package manager (check the list of files pushed in the rTorrent package).

Thus, it is largely assumed that the user will write their *own* rtorrent.rc for their own uses. And yes, reading documentation is a requirement in that regard -- claiming anything other than is, quite simply, negligence. Copy-pasting configs you found on github without knowing what option is enabled for what is, also simply put, laziness. If your car gets stolen because you didn't have time to read the manual to figure out how to lock it, do you think the insurance company will reimburse you for your loss? The only thing that was exploited in this instance, is the user's negligence.

That said, I have not seen a single "configuration guide" of rTorrent for ruTorrent that suggests that the user should use any value other than `127.0.0.1:*` for the setting `network.scgi.open_port`. In this instance binding to localhost is actually the correct configuration because it removes the ability for this port to be accessed through external routes (though it still leaves local attack vectors). Further, by the time you've bound that scgi port to an RPC mount, you have now left the realm of the responsiblity of the rTorrent dev and are now relying on Apache/nginx configs which are solely the responsibility of the user to write.

Finally, ruTorrent is *** absolutely not*** a default setting of rTorrent, which is where this vulnerability is coming into play. It is a third-party application that requires altering the configs of rTorrent to behave in a way that is needed for ruTorrent to function.

I'll close out with quote directly from the developer in regards to this issue:

> There is no patch as the vulnerability is due to a lack of knowledge about what is exposed when enabling RPC functionality, rather than a fixable flaw in the code. It was always assumed, from my perspective, that the user would ensure they properly handled access restriction.
>
> No 'default behavior' for rpc is enabled by rtorrent, and using unix sockets for RPC is what I'm recommending.
>
> The failure in this case is perhaps that I've created a piece of software that is very flexible, yet not well enough documented that regular users understand all the pitfalls.

**Comment by attritionorg** [comment]
Excellent, thank you for the details and confirmation!

**Comment by dwinnert** [comment]
Thanks! This cleared up all the BS I was seeing.

**Comment by liaralabs** [comment]
I have just merged 505aef56991f978b0d7a85cdf9333ee81c62beeb (along with the rest of v1.2) to master which switches us all over from TCP sockets to the recommended unix sockets.

It wasn't an issue before and it's even less of an issue now! Rejoice :smile:
