### ISSUE TITLE
Block public torrent

### ISSUE THREAD

**Issue by mrlongshen** [liaralabs/swizzin#68]
How to block public torrent ? 
like box install blocking ?

**Comment by liaralabs** [comment]
Currently there is not a way to block public torrents. There are a couple issues in the impelmentation that QuickBox provides:

1) iptables can slow down the machine when you have a lot of entries in iptables. This is because each and every packet that's sent needs to be matched against the iptables.

2) many entries in the hosts file are not actually proper entires, i.e.:
```
0.0.0.0 104.28.1.30:8080
```
Hosts files do not work for IPs -- this is a DNS resolution file. Further, you cannot specify ports to block, you need to redirect the entire entry to a new address.

At this time, it is a large undertaking to clean up this method and it's pretty low on my list of priorities right now. Further, in my experience, the blocking provided by this implementation leaves a bit to be desired as is... I haven't found it to be super consistent.

I'm open to implementing something of the sort, but I haven't exactly found an implementation that I'm in love with yet.

**Comment by mrlongshen** [comment]
Ok. Thanks for the explanation.
