### ISSUE TITLE
SAB Download failed - Not on your server(s)

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#7]
Getting this error on EVERY nzb I try: Download failed - Not on your server(s). Tested on known good NZB that downloads on my QB Seedhost server, same configs.

**Comment by liaralabs** [comment]
This is a little bit harder for me to troubleshoot because I don't use nzbs and don't have access to any; however, Google shows that is more a server side issue than anything:

https://www.reddit.com/r/usenet/comments/4p27m1/provider_problem_download_failed_not_on_your/

Otherwise, I need sab logs to diagnose, but the only differing configuration option between swizzin and QB is that swizzin pulls the stable branch, but QB pulls the dev.

**Comment by d2dyno** [comment]
Update:
I did another fresh install, waited until after the install process, to do `box install sabnzbd` and it works now.
