### ISSUE TITLE
Additional Request: Webmin Module

### ISSUE THREAD

**Issue by mrlongshen** [liaralabs/swizzin#70]
Hi, any changes to get a box install webmin for manage the server ? If not, how to webmin module run behind the nginx ? Thanks you.

**Comment by liaralabs** [comment]
I'm probably not likely to end up including webmin in the packages as I'm not a major fan of the application: it causes some security issues and the repo itself is also quite slow and can increase `apt update` and `apt upgrade` times significantly due to slow link speeds.

However, this should be a good place to start for a webmin nginx conf. You'll want to add a conf file `webmin.conf` to `/etc/nginx/apps` with the `location /webmin {}` directive.

https://serverfault.com/questions/443482/proxying-webmin-with-nginx

Pay careful attention to slashes ;) Consider adding basic auth ontop of the regular user auth to help prevent brute-force attacking through this channel

**Comment by mrlongshen** [comment]
Ok. Thanks for this. I just want auto script from box blah blah blah. Its much easy. Thanks you.

**Comment by mrlongshen** [comment]
Ok. Thanks for this. I just want auto script from box .... blah blah blah. Its much easy. Thanks you.
