### ISSUE TITLE
Emby - 502 Bad Gateway

### ISSUE THREAD

**Issue by 2wenty2wo** [liaralabs/swizzin#80]
Hi,

I just installed Emby via box.
Emby always displays "Disabled" in the dash, clicking on it doesn't start it".
Clicking "Refresh" doesn't do anything.

Clicking on "Emby" in the menu it displays "502 Bad Gateway ------  nginx"

Why won't Emby start?

**Comment by liaralabs** [comment]
Can I get a bit more info about your OS and version?

Installer currently works fine for me on Debian 9.

**Comment by dangitDepa** [comment]
That might be because the script doesn't actually install anything. I just tried on my test vm with Ubuntu 16.04 on it and it just doesn't install the package, nor does it create the systemd service

**Comment by liaralabs** [comment]
Weird... I'm actually grabbing the version straight from os-release because when I constructed this command the version didn't contain the extra point releases -- and they still don't on debian. I've done a little extra trimming and removed extra .* from the version and this should now allow you to continue using the repository as intended
