### ISSUE TITLE
chsh: PAM: Authentication failure

### ISSUE THREAD

**Issue by Placinta** [liaralabs/swizzin#82]
Initial installation of swizzin, once it asks for a password to set permissions for the 'seedbox' user, it prints: `chsh: PAM: Authentication failure`

log excerpt:

```
...
Creating new user seedbox ...
Adding password for user seedbox
Adding password for user seedbox
Installing nginx
Installing rtorrent
Installing rTorrent Dependencies ...
Building xmlrpc-c from source ...
Building libtorrent from source ...
Building rtorrent from source ...
Making seedbox directory structure ...
Setting permissions on seedbox ...
Password:
chsh: PAM: Authentication failure
setting up rtorrent.rc ...
Installing rutorrent
...
```
Is that normal?
I'm running Ubuntu 16.04, zsh shell.

**Comment by liaralabs** [comment]
This shouldn't actually be running here -- some cruft from the old Swizards setup. If you set added a user before install and set your shell, obviously we should respect that. Otherwise when users are added it should default to bash (if you have changed the system default then whatever you set it as).

You can safely ignore this message, I'll remove the corresponding code.
