### ISSUE TITLE
Installation of services for other users

### ISSUE THREAD

**Issue by Whisper40** [liaralabs/swizzin#90]
Hello, i just installed radarr and others, i create 3 users, but i'm the only one who have radarr, why others don't have it ?
It's possible for you to add this functionnality ?

That's a real good idea the miner ! i do it ;)

**Comment by liaralabs** [comment]
Not every application in swizzin is considered for multi-user usage. Generally speaking, swizzin assumes that extra users are created with the intention of sharing your server with your friends, but not having access to all the bells and whistles of the "master" user. The things that are shareable are typically things like download clients (rtorrent, deluge, nzbget).

Because of this, we assume a single media library and collection which would potentially be used in conjunction with Plex. Since Plex cannot be run in a multi-user environment without extra work, there is a little reason for automation applications such as Sonarr and Radarr to be running under sub-users because they cannot be used in conjunction with Plex.

I consider the addition of multi-user Plex (and subsequent media automation apps) to be a professional feature, mostly used for the intention of reselling slots on your machine. As swizzin (vanilla) is freely provided as a solution to hobbyists, I tend to avoid features desired by those looking to turn a profit with my management as a base. (not saying you are, specifically) If ever these features were provided to the public, it would be in the form of a paid solution.

**Comment by Whisper40** [comment]
Hum ok i understand, but Quickbox will release in 6 days the new version of quickbox called Pro, we don't know the price but we should be able to install services for all users.
I only want that for sharing with friends
