### ISSUE TITLE
Ombi Service Issue

### ISSUE THREAD

**Issue by Somnambulated** [liaralabs/swizzin#92]
The Ombi service is having some kind of issue - I'm not sure how to narrow it down. 

It shows a red status light in the panel - when I "Systemctl status ombi" it shows inactive (dead) but when I "systemctl start ombi" it shows "success" - yet, still inactive (dead) status

I don't see a log file for Ombi

I've tried removing/re-installing via box

Is there a configuration step I missed? How can I troubleshoot it? 

It seems worth mentioning that when I "box upgrade ombi" it hangs after "cannot create directory: already exists"

**Comment by liaralabs** [comment]
Turns out there are a couple issues with the Ombi script at the moment.

The dev (somewhat) recently started pushing the v3 images as stable to the Releases page, which has mucked up my previous scripting. I used to grep for a zip file on the releases page, but now this pulls the Windows image instead because the dev has chosen to distrubute a tar for linux instead.

As a temporary stop gap, I'm hard coding the last v2 release into the update script because base urls in v3 aren't quite ready yet.

**Comment by Somnambulated** [comment]
Gah, I *thought* that was happening - I noted a bunch of .exe and windows.dll files that I didn't think Linux ever used.

What do I need to do to make this happen? 

I tried "box upgrade ombi" - which ran & altered some files as shown in your latest commit, but that didn't fix the issue. 

I then tried to 'box remove ombi' and 'box install ombi' - but again, no dice. 

Do I need to do something else?

**Comment by liaralabs** [comment]
Well it *is* a Windows program and mono is what makes it work under Linux,
so what you're experiencing is normal for v2. V3 moved to the new .net core
which actually works natively under Linux without any sort of emulation.

I tested this as a fresh install on my test server and it did install
(whereas the previous version was hanging as you noted).

`box upgrade *` should have triggered a repo update, which I think you had.

However I'd just give this a shot

```
box update
/etc/swizzin/scripts/remove/ombi.sh
box install ombi
```

If the service still isn't running, we need to go into troubleshooting mode.

Try
`journalctl -u ombi.service` (you may need to scroll through several pages
of output.

Or

`journalctl -f -u omni.service` (this will "tail" the output of journalctl
and follow it, so you could run systemctl restart ombi in another session
and watch the logging in the other)

If that doesn't give anything useful, then just run the command straight
from the systemd service. Make sure you are currently in a shell for your
master user and run

```
mono /opt/ombi/Ombi.exe -p 3000 --base ombi
```

If the program fails to start, it will error and should give you a reason
why.

**Comment by Somnambulated** [comment]
Ah, good to know - I thought there were unique versions for each OS.

Okay, so - 

1. I tried box update && /etc/swizzin/scripts/remove/ombi.sh && box install ombi
It ran successfully, but no dice.

2. journalctl -u ombi.service (and journalctl -f -u ombi.service) both returned very little (to me anyway)
[/etc/systemd/system/ombi.service:1] Assignment outside of section. Ignoring.
[/etc/systemd/system/ombi.service:2] Assignment outside of section. Ignoring. 
(21 lines of these 2 messages)

3. mono /opt/ombi/Ombi.exe -p 3000 --base ombi
(I tried putting this in pastebin but it wouldn't cooperate, so bare with me): 
Starting Up! Please wait, this can usually take a few seconds.
Version: 2.2.1678
Location of the database: /opt/ombi/Ombi.sqlite
[ERROR] FATAL UNHANDLED EXCEPTION: Nlog.NLogConfigurationException: Error when setting property 'Format' on Layout Renderer: ${exception} ---> System.ArgumentException: Object of type 'System.ReadOnlySpan'1[System.Char]' cannot be converted to type 'System.String'.
    at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00071] in <659842057...>:0
  at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParamterInfo[] pinfo, System.Globalization.CultureInfo culture, System...

This continues on for ~40 lines - all referring to different System.Reflection.Method(s) & NLog.Layouts - though I'm guessing the error is related to the first line about unhandled exceptions?

Thanks for the help on this, by the way!

**Comment by liaralabs** [comment]
Okay, think I've gotten to the root of the issue you're experiencing now. I'm just running some tests and will hopefully be able to push the fix soon.

**Comment by liaralabs** [comment]
Okay, I just pushed 5f9f1a4343f70b5171105169cd91bce48813033e which has an auto-update script that should downgrade your mono version from 5.10 (bleeding edge stable) to something a little more stable (what your Distribution packages or what Sonarr packages -- depending if you're running Xenial or not).

I tested this script on Artful, Xenial, Stretch and Jessie (I also found other bugs and fixed them too in the case of Jessie). There should be no reason to have it fix Bionic because it's not out yet and the setup has now been altered for future installs.

Please test with a `box update`. Once finished, if you `systemctl start ombi` pray that it is working. Otherwise if it still isn't, wait a few days because the Ombi dev just pushed the fix for v3 to master as I was working on this. In that case, we can trash this and get on with our lives with one less mono app to clutter it up.

**Comment by Somnambulated** [comment]
You move quick 😀 

I'm doing some media library backups, and unfortunately I haven't been able to get my samba shares working, so the server is offline for another ~2 hours, but I'll give this a shot as soon as it's back up.

If I have to wait a few days for the Ombi update, I imagine I will survive :)

**Comment by Somnambulated** [comment]
Update: 

Would any of these updates changed Sonarr or rTorrent in some way? 

Sonarr & Radarr stopped connecting to rTorrent - I tried going through the range of options (changing URL path, changed host to localhost/127.0.0.1, tried disabling SSL) - but it just says it can't connect

Both services are green dot & rtorrent does indeed seem to be working.

**Comment by Somnambulated** [comment]
No worries! I just thought I’d make sure it wasn’t something I did. 

It seems I have a tendency to bork my Linux installs, even when simply following directions.
