### ISSUE TITLE
Can't link rTorrent with sonarr

### ISSUE THREAD

**Issue by Tirkoue** [liaralabs/swizzin#94]
Fresh install on debian9, rtorrent with flood frontend, letsencrypt with custom domain.
I'm using /user path because I don't have rutorrent:

```
Host: 127.0.0.1
Port: 443
URL Path: /{username}
Username: {username}
Password: {password}
SSL: On
```

Sonarr error :
```
Unable to connect to rTorrent, please check your settings ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Error while sending TLS Alert (Fatal:InternalError): System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
```
I can provide further information if needed. I didn't (manually) touch nginx conf.

**Comment by liaralabs** [comment]
@Somnambulated @Tirkoue this should now be fixed (hopefully!) --

`box update` should pull in the new changes for you and update your mono to snapshot 4.8. Unfortunately, the side effect of this fix is that there is a new warning any time you apt-get update; however you can ignore this.

**Comment by liaralabs** [comment]
The only reason 5.10 would still be recommended at this point is if you have a mono repository outside of the version controlled ones.

/etc/apt/sources.list.d should only have one reference in it with the official mirror and it's wheezy/snapshot/4.8. Any reference without will prefer the latest version 5.10.

The manual way to do this is simply `apt remove mono-complete` then `apt autoremove` then reinstall mono complete (and Sonarr because the package will be removed if mono is too).

I'm fairly certain ombi was working under 4.8.

I could go back to pushing bleeding edge mono, but I don't find the rolling release offers anything but troubles and crashes.

**Comment by Somnambulated** [comment]
It's using 4.8

Sorry if that update trail was confusing. 

Something broke and it was stuck using 4.2 - but when I used the aptitude install it removed mono-complete, then installed the proper 4.8 packages and everything started working fine.

No need to update from where I sit :)

**Comment by liaralabs** [comment]
Wonderful, glad it's working!

Aptitude is amazing -- it was the basis for the downgrade script that ran the first time

**Comment by Somnambulated** [comment]
I've only used it a few times but it is indeed amazing & has saved me from a bunch of frustration

**Comment by Tirkoue** [comment]
Thanks @liaralabs for your amazing reactivity ...

The mono update fixed the previous problem, but I still can't connect to rTorrent ...

My new issue is : ` NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to rTorrent, please check your settings ---> CookComputing.XmlRpc.XmlRpcServerException: Not Found`

Still same setup.
I did `box update` then `box remove sonarr radarr` then `reboot` then `box install sonarr radarr`.

**Comment by liaralabs** [comment]
Ah, you're definitely experiencing a different issue now -- Sonarr just can't find the xmlrpc server you've defined. Likely because Flood doesn't actually install the rpc endpoints. It does now though ;)

`box update` should pull in the new changes and give you the file /etc/nginx/apps/{username}.scgi.conf, then reload nginx -- that endpoint should be functional now.
